In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Variable para la ruta, se lee correctamente, se genera el indices

In [15]:
# para leer el archivo de sf_cyberpunk.ipynb 
df = pd.read_csv("sf_cyberpunk.csv")

  
# Mostrando primera 5 filas
df.head()

,Book_Title,Original_Book_Title,Author_Name,Edition_Language,Rating_score,Rating_votes,Review_number,Book_Description,Year_published,Genres,url
0,Neuromancer,Neuromancer,William Gibson,English,3.90,268536,9800,Hotwired to the leading edges of art and techn...,1984,"{'Science Fiction': 6796, 'Fiction': 3550, 'Sc...",https://www.goodreads.com/book/show/6088007-ne...
1,Snow Crash,Snow Crash,Neal Stephenson,English,4.02,241095,9391,"In reality, Hiro Protagonist delivers pizza fo...",1992,"{'Science Fiction': 5069, 'Fiction': 3067, 'Sc...",https://www.goodreads.com/book/show/40651883-s...
2,Count Zero,Count Zero,William Gibson,English,4.01,46114,1219,A corporate mercenary wakes in a reconstructed...,1986,"{'Science Fiction': 1480, 'Science Fiction (Cy...",https://www.goodreads.com/book/show/22200.Coun...
3,Altered Carbon,Altered Carbon,Richard K. Morgan,English,4.05,90069,5990,Four hundred years from now mankind is strung ...,2002,"{'Science Fiction': 3185, 'Fiction': 1087, 'Sc...",https://www.goodreads.com/book/show/40792913-a...
4,Mona Lisa Overdrive,Mona Lisa Overdrive,William Gibson,English,3.99,37399,957,"William Gibson, author of the extraordinary mu...",1988,"{'Science Fiction': 1337, 'Science Fiction (Cy...",https://www.goodreads.com/book/show/154091.Mon...

In [16]:
df.tail()
# Mostrando ultimos 5 filas

,Book_Title,Original_Book_Title,Author_Name,Edition_Language,Rating_score,Rating_votes,Review_number,Book_Description,Year_published,Genres,url
1239,Currency,"The System of the World (The Baroque Cycle, #3)",Neal Stephenson,English,4.41,1031,31,This is the middle third of the volume origina...,2003,"{'Fiction': 22, 'Historical (Historical Fictio...",https://www.goodreads.com/book/show/227968.Cur...
1240,King of the Vagabonds,King of the Vagabonds,Neal Stephenson,English,4.17,2161,124,"A chronicle of the breathtaking exploits of ""H...",2004,"{'Historical (Historical Fiction) ': 58, 'Fict...",https://www.goodreads.com/book/show/2016.King_...
1241,Odalisque,Quicksilver,Neal Stephenson,English,4.20,1753,85,The trials of Dr. Daniel Waterhouse and the Na...,2005,"{'Historical (Historical Fiction) ': 39, 'Fict...",https://www.goodreads.com/book/show/829.Odalisque
1242,An Unwelcome Quest,B00MRADM1K,Scott Meyer,English,3.99,14968,770,Ever since Martin Banks and his fellow compute...,2015,"{'Fantasy': 434, 'Fiction': 141, 'Science Fict...",https://www.goodreads.com/book/show/23249416-a...
1243,Vortex,Vortex,S.J. Kincaid,English,4.28,6549,552,The impossible was just the beginning. Now in ...,2013,"{'Science Fiction': 149, 'Young Adult': 146, '...",https://www.goodreads.com/book/show/16101515-v...

In [17]:
df.describe()
#Cómo calcular data descriptivo estatisticamente?

       Rating_score  Rating_votes  Review_number  Year_published
count   1244.000000  1.244000e+03    1244.000000     1244.000000
mean       3.890957  3.942286e+04    1792.016881     1999.021704
std        0.297958  2.803274e+05    9142.208471       99.208575
min        2.500000  8.000000e+00       0.000000        0.000000
25%        3.690000  2.477500e+02      20.000000     1996.000000
50%        3.890000  9.510000e+02      79.000000     2007.000000
75%        4.110000  6.280250e+03     471.000000     2014.000000
max        4.820000  6.572148e+06  174079.000000     2021.000000

In [22]:
df_filtrated = df.fillna(0)
df_filtrated.head()

,Book_Title,Original_Book_Title,Author_Name,Edition_Language,Rating_score,Rating_votes,Review_number,Book_Description,Year_published,Genres,url
0,Neuromancer,Neuromancer,William Gibson,English,3.90,268536,9800,Hotwired to the leading edges of art and techn...,1984,"{'Science Fiction': 6796, 'Fiction': 3550, 'Sc...",https://www.goodreads.com/book/show/6088007-ne...
1,Snow Crash,Snow Crash,Neal Stephenson,English,4.02,241095,9391,"In reality, Hiro Protagonist delivers pizza fo...",1992,"{'Science Fiction': 5069, 'Fiction': 3067, 'Sc...",https://www.goodreads.com/book/show/40651883-s...
2,Count Zero,Count Zero,William Gibson,English,4.01,46114,1219,A corporate mercenary wakes in a reconstructed...,1986,"{'Science Fiction': 1480, 'Science Fiction (Cy...",https://www.goodreads.com/book/show/22200.Coun...
3,Altered Carbon,Altered Carbon,Richard K. Morgan,English,4.05,90069,5990,Four hundred years from now mankind is strung ...,2002,"{'Science Fiction': 3185, 'Fiction': 1087, 'Sc...",https://www.goodreads.com/book/show/40792913-a...
4,Mona Lisa Overdrive,Mona Lisa Overdrive,William Gibson,English,3.99,37399,957,"William Gibson, author of the extraordinary mu...",1988,"{'Science Fiction': 1337, 'Science Fiction (Cy...",https://www.goodreads.com/book/show/154091.Mon...

In [20]:
df_filtrated = df.dropna()
df_filtrated.head()
#¿Cómo eliminar de la lista de datos de Excel?

,Book_Title,Original_Book_Title,Author_Name,Edition_Language,Rating_score,Rating_votes,Review_number,Book_Description,Year_published,Genres,url
0,Neuromancer,Neuromancer,William Gibson,English,3.90,268536,9800,Hotwired to the leading edges of art and techn...,1984,"{'Science Fiction': 6796, 'Fiction': 3550, 'Sc...",https://www.goodreads.com/book/show/6088007-ne...
1,Snow Crash,Snow Crash,Neal Stephenson,English,4.02,241095,9391,"In reality, Hiro Protagonist delivers pizza fo...",1992,"{'Science Fiction': 5069, 'Fiction': 3067, 'Sc...",https://www.goodreads.com/book/show/40651883-s...
2,Count Zero,Count Zero,William Gibson,English,4.01,46114,1219,A corporate mercenary wakes in a reconstructed...,1986,"{'Science Fiction': 1480, 'Science Fiction (Cy...",https://www.goodreads.com/book/show/22200.Coun...
3,Altered Carbon,Altered Carbon,Richard K. Morgan,English,4.05,90069,5990,Four hundred years from now mankind is strung ...,2002,"{'Science Fiction': 3185, 'Fiction': 1087, 'Sc...",https://www.goodreads.com/book/show/40792913-a...
4,Mona Lisa Overdrive,Mona Lisa Overdrive,William Gibson,English,3.99,37399,957,"William Gibson, author of the extraordinary mu...",1988,"{'Science Fiction': 1337, 'Science Fiction (Cy...",https://www.goodreads.com/book/show/154091.Mon...